version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8npass
      POSTGRES_DB: n8ndb
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    networks:
      - n8n-net
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - n8n-net
    restart: unless-stopped 

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8ndb
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8npass
      - GENERIC_TIMEZONE=America/Santo_Domingo
      - TZ=America/Santo_Domingo
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - n8n-data:/home/node/.n8n
    networks:
      - n8n-net
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

volumes:
  postgres-data:
  n8n-data:

networks:
  n8n-net:
    driver: bridge

    