services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./hass-config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    networks:
      - hass-network

  nodered:
    container_name: nodered
    image: nodered/node-red
    environment:
      - TZ=America/Santo_Domingo
    ports:
      - 1880:1880
    volumes:
      - ./nodered:/data
    depends_on:
      - homeassistant
      - mosquitto
    restart: unless-stopped
    networks:
      - hass-network

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    environment:
      - TZ=America/Santo_Domingo
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - "./mosquitto/config:/mosquitto/config"
      - "./mosquitto/data:/mosquitto/data"
      - "./mosquitto/log:/mosquitto/log"
      - "./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf"
    restart: unless-stopped
    networks:
      - hass-network

  code-server:
    container_name: code_server
    image: lscr.io/linuxserver/code-server:latest
    environment:
      - TZ=America/Santo_Domingo
      - DEFAULT_WORKSPACE=/config
    ports:
      - 8443:8443
    volumes:
      - ./hass-config:/config
    restart: unless-stopped
    networks:
      - hass-network

networks:
  hass-network:
    driver: bridge