services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"  
      TYPE: "FORGE"
      VERSION: "1.20.1"
      FORGE_VERSION: "47.1.3" 
      MEMORY: "10G"
    volumes:
      - ./data:/data

      